name: CI/CD tests

on:
  push:

jobs:
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: 'Setup'
        run: flutter pub get

      - name: 'Format'
        run: flutter format lib/** --set-exit-if-changed

      - name: "Run tests"
        run: flutter test -r expanded
